// 8-bit pixel-art icons. Each icon is an array of rows; every character maps to
// a color in PALETTE (space = transparent). Rows are padded automatically by the
// renderer, so they don't all need to be the same length.

export const PALETTE: Record<string, string> = {
  k: "#23232f", // outline / dark
  w: "#f7f7fb", // white / paper
  y: "#f4c430", // folder yellow / star
  o: "#ee7b30", // orange
  O: "#c75c1e", // dark orange
  r: "#e0484d", // red
  g: "#46c05a", // green
  G: "#2f7d3a", // dark green
  b: "#3b6fe0", // blue
  B: "#22397f", // dark blue
  c: "#5fd0e0", // cyan glass
  n: "#a06a35", // brown
  N: "#6e4420", // dark brown
  s: "#c6c9d4", // silver
  d: "#5b6070", // gray
  l: "#f1c79b", // skin
  p: "#9b5cf0", // purple
};

export const ICONS: Record<string, string[]> = {
  about: [
    "....kkkkkk....",
    "...kllllllk...",
    "...kllllllk...",
    "...kllllllk...",
    "...kllllllk...",
    "....kllllk....",
    "...kbbbbbbk...",
    "..kbbbbbbbbk..",
    ".kbbbbbbbbbbk.",
    ".kbbbbbbbbbbk.",
    ".kbbbbbbbbbbk.",
    ".kbbbbbbbbbbk.",
    ".kbbbbbbbbbbk.",
    ".kkbbbbbbbbkk.",
  ],
  resume: [
    ".kkkkkkkkkkk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkkwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkkwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkkwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkwwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkwwwk.",
    ".kwwwwwwwwwk.",
    ".kkkkkkkkkkk.",
  ],
  file: [
    ".kkkkkkkkkkk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkkwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkkwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkkwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkkwwk.",
    ".kwwwwwwwwwk.",
    ".kwkkkkkwwwk.",
    ".kwwwwwwwwwk.",
    ".kkkkkkkkkkk.",
  ],
  projects: [
    "..............",
    "..kkkkk.......",
    ".kyyyyyk......",
    "kkkkkkkkkkkkk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kkkkkkkkkkkkk.",
  ],
  folder: [
    "..............",
    "..kkkkk.......",
    ".kyyyyyk......",
    "kkkkkkkkkkkkk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kyyyyyyyyyyyk.",
    "kkkkkkkkkkkkk.",
  ],
  work: [
    ".....kkkk.....",
    ".....k..k.....",
    "..kkkkkkkkkk..",
    ".knnnnnnnnnnk.",
    ".knnnnnnnnnnk.",
    ".knnnkkkknnnk.",
    ".knnnk..knnnk.",
    ".knnnk..knnnk.",
    ".knnnkkkknnnk.",
    ".knnnnnnnnnnk.",
    ".knnnnnnnnnnk.",
    ".kkkkkkkkkkkk.",
  ],
  briefcase: [
    ".....kkkk.....",
    ".....k..k.....",
    "..kkkkkkkkkk..",
    ".knnnnnnnnnnk.",
    ".knnnnnnnnnnk.",
    ".knnnkkkknnnk.",
    ".knnnk..knnnk.",
    ".knnnk..knnnk.",
    ".knnnkkkknnnk.",
    ".knnnnnnnnnnk.",
    ".knnnnnnnnnnk.",
    ".kkkkkkkkkkkk.",
  ],
  amazon: [
    ".kkkkkkkkkk.",
    ".knnnnnnnnk.",
    ".knnnnnnnnk.",
    ".kkkkkkkkkk.",
    ".knnnknnnnk.",
    ".knnnknnnnk.",
    ".knnnknnnnk.",
    ".knnnknnnnk.",
    ".kkkkkkkkkk.",
  ],
  github: [
    "..d........d..",
    "..dd......dd..",
    "..ddd....ddd..",
    "..dddddddddd..",
    ".dddddddddddd.",
    ".dwwddddddwwd.",
    ".dwkddddddkwd.",
    ".dddddddddddd.",
    ".dddkwwwwkddd.",
    ".dddddddddddd.",
    "..dddddddddd..",
    "...d.d..d.d...",
  ],
  basketball: [
    "...oooooo...",
    ".ooookooooo.",
    "oooookoooooo",
    "oookoookoooo",
    "ookooookoooo",
    "kkkkkkkkkkkk",
    "ookooookoooo",
    "oookoookoooo",
    "oooookoooooo",
    ".ooookooooo.",
    "...oooooo...",
  ],
  photography: [
    ".....kkkk.....",
    "...kkkkkkkk...",
    ".kkkkkkkkkkkk.",
    ".kddddddddddk.",
    ".kdddbbbbdddk.",
    ".kddbccccbddk.",
    ".kddbccccbddk.",
    ".kddbccccbddk.",
    ".kdddbbbbdddk.",
    ".kddddddddddk.",
    ".kkkkkkkkkkkk.",
  ],
  comics: [
    "......kk......",
    "...k..kk..k...",
    "....k.kk.k....",
    ".k..kyyyyk..k.",
    "..kkyyyyyykk..",
    "...kyyyyyyk...",
    ".kkyyyyyyyykk.",
    "kyyyyyyyyyyyyk",
    ".kkyyyyyyyykk.",
    "...kyyyyyyk...",
    "..kkyyyyyykk..",
    ".k..kyyyyk..k.",
    "....k.kk.k....",
    "...k..kk..k...",
  ],
  contact: [
    "kkkkkkkkkkkkkk",
    "kwwwwwwwwwwwwk",
    "kwkwwwwwwwwkwk",
    "kwwkwwwwwwkwwk",
    "kwwwkwwwwkwwwk",
    "kwwwwkwwkwwwwk",
    "kwwwwwkkwwwwwk",
    "kwwwwwwwwwwwwk",
    "kwwwwwwwwwwwwk",
    "kkkkkkkkkkkkkk",
  ],
  trash: [
    "....kkkk....",
    ".kkkkkkkkkk.",
    "..ksssssssk.",
    "..ksdsdsdsk.",
    "..ksdsdsdsk.",
    "..ksdsdsdsk.",
    "..ksdsdsdsk.",
    "..ksdsdsdsk.",
    "..ksssssssk.",
    "...kkkkkkk..",
  ],
  display: [
    "kkkkkkkkkkkk",
    "kbbbbbbbbbbk",
    "kbccccccccbk",
    "kbccccccccbk",
    "kbccccccccbk",
    "kbccccccccbk",
    "kbbbbbbbbbbk",
    "kkkkkkkkkkkk",
    "....kkkk....",
    "...kkkkkkk..",
  ],
  star: [
    ".....kk.....",
    ".....kk.....",
    "....kyyk....",
    "kkkkkyykkkkk",
    ".kyyyyyyyyk.",
    "..kyyyyyyk..",
    "..kyyyyyyk..",
    ".kyykkyykk..",
    ".kyk..kyk...",
    ".kk....kk...",
  ],
  terminal: [
    "kkkkkkkkkkkk",
    "kddddddddddk",
    "kdgddddddddk",
    "kddgdddddddk",
    "kdgddddddddk",
    "kdddddwwdddk",
    "kddddddddddk",
    "kkkkkkkkkkkk",
  ],
  notes: [
    ".kkkkkkkkkk.",
    ".kyyyyyyyyk.",
    ".kyrrrrrryk.",
    ".kyyyyyyyyk.",
    ".kyrrrrrryk.",
    ".kyyyyyyyyk.",
    ".kyrrrrrryk.",
    ".kyyyyyyyyk.",
    ".kkkkkkkkkk.",
  ],
  link: [
    "...kk.....",
    "..kbbk....",
    "..kbbk....",
    "...kkkk...",
    "....kbbk..",
    "....kbbk..",
    ".....kk...",
  ],
  mail: [
    "kkkkkkkkkkkk",
    "kwwwwwwwwwwk",
    "kkwwwwwwwwkk",
    "kwkkwwwwkkwk",
    "kwwkkwwkkwwk",
    "kwwwkkkkwwwk",
    "kwwwwwwwwwwk",
    "kwwwwwwwwwwk",
    "kkkkkkkkkkkk",
  ],
  phone: [
    ".kkkkkk.",
    ".kwwwwk.",
    ".kggggk.",
    ".kggggk.",
    ".kggggk.",
    ".kggggk.",
    ".kggggk.",
    ".kggggk.",
    ".kwwwwk.",
    ".kwkkwk.",
    ".kkkkkk.",
  ],
  linkedin: [
    "kkkkkkkkkkkk",
    "kBBBBBBBBBBk",
    "kBwBBBBBBBBk",
    "kBBBBBBBBBBk",
    "kBwBBwwwBBBk",
    "kBwBBwBwBBBk",
    "kBwBBwBwBBBk",
    "kBwBBwBwBBBk",
    "kBBBBBBBBBBk",
    "kkkkkkkkkkkk",
  ],
  x: [
    "kkkkkkkkkk",
    "kwkkkkkkwk",
    "kkwkkkkwkk",
    "kkkwkkwkkk",
    "kkkkwwkkkk",
    "kkkkwwkkkk",
    "kkkwkkwkkk",
    "kkwkkkkwkk",
    "kwkkkkkkwk",
    "kkkkkkkkkk",
  ],
  instagram: [
    "kkkkkkkkkk",
    "kppppppppk",
    "kppppppwpk",
    "kppwwwwppk",
    "kppwppwppk",
    "kppwppwppk",
    "kppwwwwppk",
    "kppppppppk",
    "kppppppppk",
    "kkkkkkkkkk",
  ],
};
